version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3305:3305
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass