version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '8080:8080'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass